{% set name = "aiormq" %}
{% set version = "6.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c1a5744af35b277764e72bfbb4dc15372533f03bd435f5331d47b79fd45148cc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pamqp ==3.0.1
    - yarl

test:
  imports:
    - aiormq

about:
  home: https://github.com/mosquito/aiormq
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: aiormq is a pure python AMQP client library

  description: |
    aiormq is a pure python AMQP client library
  doc_url: https://github.com/mosquito/aiormq
  dev_url: https://github.com/mosquito/aiormq

extra:
  recipe-maintainers:
    - gregfreeman
