{% set name = "aiormq" %}
{% set version = "6.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e7c01b662804e1cc7ace9a17794e8c1192a27fc2afa96162362a6e61ae8e8ef

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - pamqp ==3.3.0
    - yarl

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - aiormq
  commands:
    - pip check

about:
  home: https://github.com/mosquito/aiormq
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: aiormq is a pure python AMQP client library

  description: |
    aiormq is a pure python AMQP client library
  doc_url: https://github.com/mosquito/aiormq
  dev_url: https://github.com/mosquito/aiormq

extra:
  recipe-maintainers:
    - gregfreeman
    - sphuber
